// Package localrun owns the disposable, Docker-backed nvoken quickstart.
package localrun

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	containerImage = "postgres:17-alpine"
	containerLabel = "io.nvoken.quickstart"
	containerName  = "nvoken-quickstart-postgres"
	fileMarker     = "# Generated by nvokend quickstart. Disposable local use only."
)

var providerVariables = map[string]string{
	"anthropic": "ANTHROPIC_API_KEY",
	"openai":    "OPENAI_API_KEY",
}

type DockerRunner func(context.Context, ...string) (string, error)

type Options struct {
	Provider    string
	Model       string
	OutputPath  string
	Environment map[string]string
	Docker      DockerRunner
	Random      io.Reader
	Output      io.Writer
}

type Result struct {
	Provider    string
	Environment map[string]string
}

func Prepare(ctx context.Context, options Options) (Result, error) {
	options = defaults(options)
	options.Provider = strings.ToLower(strings.TrimSpace(options.Provider))
	options.Model = strings.TrimSpace(options.Model)
	path, err := filepath.Abs(options.OutputPath)
	if err != nil {
		return Result{}, fmt.Errorf("resolve quickstart environment path: %w", err)
	}

	if content, readErr := os.ReadFile(path); readErr == nil {
		info, statErr := os.Lstat(path)
		if statErr != nil {
			return Result{}, fmt.Errorf("inspect quickstart environment: %w", statErr)
		}
		if !info.Mode().IsRegular() {
			return Result{}, fmt.Errorf("refusing to use non-regular quickstart environment %s", path)
		}
		provider, values, parseErr := parseExisting(content)
		if parseErr != nil {
			return Result{}, parseErr
		}
		if options.Provider != "" && options.Provider != provider {
			return Result{}, fmt.Errorf("existing %s selects %s, not %s; run quickstart cleanup and remove the file to change it", path, provider, options.Provider)
		}
		if options.Provider == "" {
			options.Provider = provider
		}
		existingModel := values["NVOKEN_MODEL"]
		if options.Model != "" && options.Model != existingModel {
			return Result{}, fmt.Errorf("existing %s selects model %s, not %s; run quickstart cleanup and remove the file to change it", path, existingModel, options.Model)
		}
		if options.Model == "" {
			options.Model = existingModel
		}
		providerVariable := providerVariables[provider]
		if currentKey := options.Environment[providerVariable]; currentKey != "" && currentKey != values[providerVariable] {
			return Result{}, fmt.Errorf("existing %s contains a different %s; run quickstart cleanup and remove the file to use the exported key, or unset %s to reuse the saved key", path, providerVariable, providerVariable)
		}
		if err := ensurePostgres(ctx, options.Docker); err != nil {
			return Result{}, err
		}
		_, _ = fmt.Fprintf(options.Output, "Using existing %s and disposable PostgreSQL 17.\n", path)
		return Result{
			Provider:    provider,
			Environment: values,
		}, nil
	} else if errors.Is(readErr, os.ErrNotExist) {
		if info, statErr := os.Lstat(path); statErr == nil {
			return Result{}, fmt.Errorf("refusing to replace non-regular quickstart environment %s (%s)", path, info.Mode().Type())
		} else if !errors.Is(statErr, os.ErrNotExist) {
			return Result{}, fmt.Errorf("inspect quickstart environment: %w", statErr)
		}
	} else {
		return Result{}, fmt.Errorf("read quickstart environment: %w", readErr)
	}

	providerVariable, ok := providerVariables[options.Provider]
	if !ok {
		return Result{}, errors.New("--provider must be anthropic or openai")
	}
	if strings.TrimSpace(options.Model) == "" {
		return Result{}, errors.New("--model is required; use an exact model ID available to your provider account")
	}
	if strings.ContainsAny(options.Model, "\r\n") {
		return Result{}, errors.New("--model must be one line")
	}
	providerKey := options.Environment[providerVariable]
	if providerKey == "" {
		return Result{}, fmt.Errorf("export %s before running nvokend quickstart", providerVariable)
	}
	if strings.ContainsAny(providerKey, "\r\n") {
		return Result{}, fmt.Errorf("%s must be one line", providerVariable)
	}

	values, err := generatedEnvironment(options.Provider, options.Model, providerKey, options.Random)
	if err != nil {
		return Result{}, err
	}
	if err := ensurePostgres(ctx, options.Docker); err != nil {
		return Result{}, err
	}
	flags := os.O_WRONLY | os.O_CREATE | os.O_EXCL
	file, err := os.OpenFile(path, flags, 0o600)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return Result{}, fmt.Errorf("refusing to replace existing %s; run quickstart cleanup and remove the file before resetting local data", path)
		}
		return Result{}, fmt.Errorf("write quickstart environment: %w", err)
	}
	content := renderEnvironment(values)
	if _, err := io.WriteString(file, content); err != nil {
		_ = file.Close()
		return Result{}, fmt.Errorf("write quickstart environment: %w", err)
	}
	if err := file.Close(); err != nil {
		return Result{}, fmt.Errorf("close quickstart environment: %w", err)
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return Result{}, fmt.Errorf("protect quickstart environment: %w", err)
	}
	_, _ = fmt.Fprintf(options.Output, "Wrote %s with generated local secrets and %s.\n", path, providerVariable)
	return Result{
		Provider:    options.Provider,
		Environment: values,
	}, nil
}

func Cleanup(ctx context.Context, docker DockerRunner, output io.Writer) error {
	if docker == nil {
		docker = RunDocker
	}
	if output == nil {
		output = io.Discard
	}
	if _, err := docker(ctx, "version", "--format", "{{.Server.Version}}"); err != nil {
		return fmt.Errorf("Docker is required for the local quickstart: %w", err)
	}
	label, err := docker(ctx, "inspect", "--format", `{{ index .Config.Labels "`+containerLabel+`" }}`, containerName)
	if err != nil {
		if !containerMissing(err) {
			return fmt.Errorf("inspect disposable PostgreSQL container: %w", err)
		}
		_, _ = fmt.Fprintf(output, "Disposable container %s is already absent.\n", containerName)
		return nil
	}
	if strings.TrimSpace(label) != "true" {
		return fmt.Errorf("refusing to remove container %s because nvoken did not create it", containerName)
	}
	if _, err := docker(ctx, "rm", "--force", containerName); err != nil {
		return fmt.Errorf("remove disposable PostgreSQL container: %w", err)
	}
	_, _ = fmt.Fprintf(output, "Removed %s and its disposable database.\n", containerName)
	return nil
}

func RunDocker(ctx context.Context, arguments ...string) (string, error) {
	command := exec.CommandContext(ctx, "docker", arguments...)
	output, err := command.CombinedOutput()
	if err != nil {
		message := strings.TrimSpace(string(output))
		if message == "" {
			message = err.Error()
		}
		return "", errors.New(message)
	}
	return strings.TrimSpace(string(output)), nil
}

func containerMissing(err error) bool {
	message := strings.ToLower(err.Error())
	return strings.Contains(message, "no such object") || strings.Contains(message, "no such container")
}

func defaults(options Options) Options {
	if options.OutputPath == "" {
		options.OutputPath = ".env"
	}
	if options.Environment == nil {
		options.Environment = environmentMap(os.Environ())
	}
	if options.Docker == nil {
		options.Docker = RunDocker
	}
	if options.Random == nil {
		options.Random = rand.Reader
	}
	if options.Output == nil {
		options.Output = io.Discard
	}
	return options
}

func environmentMap(entries []string) map[string]string {
	values := make(map[string]string, len(entries))
	for _, entry := range entries {
		name, value, ok := strings.Cut(entry, "=")
		if ok {
			values[name] = value
		}
	}
	return values
}

func generatedEnvironment(provider string, model string, providerKey string, random io.Reader) (map[string]string, error) {
	runtimeKey, err := randomHex(random, 32)
	if err != nil {
		return nil, err
	}
	ownerSecret, err := randomHex(random, 32)
	if err != nil {
		return nil, err
	}
	deliveryBytes := make([]byte, 32)
	if _, err := io.ReadFull(random, deliveryBytes); err != nil {
		return nil, fmt.Errorf("generate credential-delivery key: %w", err)
	}
	values := map[string]string{
		"ANTHROPIC_API_KEY":                    "",
		"BOOTSTRAP_OWNER_SECRET":               ownerSecret,
		"CREDENTIAL_DELIVERY_KEY":              base64.RawURLEncoding.EncodeToString(deliveryBytes),
		"DATABASE_MAX_CONNS":                   "10",
		"DATABASE_URL":                         "postgres://nvoken:nvoken-local@127.0.0.1:55432/nvoken?sslmode=disable",
		"ENGINE_CONCURRENCY":                   "2",
		"ENGINE_DRAIN_GRACE":                   "10s",
		"INVOCATION_DEFAULT_CREDENTIAL_SOURCE": "installation_byok",
		"INVOCATION_EXECUTION_MODE":            "embedded",
		"MODEL_CREDENTIAL_DEPLOYMENT_MODE":     "self_hosted",
		"NVOKEN_API_KEY":                       runtimeKey,
		"NVOKEN_BASE_URL":                      "http://localhost:8080",
		"NVOKEN_MODEL":                         model,
		"NVOKEN_PROCESS_ROLE":                  "combined",
		"NVOKEN_PROVIDER":                      provider,
		"NVOKEN_PUBLIC_BASE_URL":               "http://localhost:8080",
		"NVOKEN_TRUST_FORWARDED_CLIENT_IP":     "false",
		"OPENAI_API_KEY":                       "",
		"PORT":                                 "8080",
		"RUNTIME_API_KEY":                      runtimeKey,
		"SHUTDOWN_TIMEOUT":                     "20s",
	}
	values[providerVariables[provider]] = providerKey
	return values, nil
}

func randomHex(random io.Reader, size int) (string, error) {
	value := make([]byte, size)
	if _, err := io.ReadFull(random, value); err != nil {
		return "", fmt.Errorf("generate local secret: %w", err)
	}
	return hex.EncodeToString(value), nil
}

func renderEnvironment(values map[string]string) string {
	order := []string{
		"NVOKEN_PROCESS_ROLE",
		"INVOCATION_EXECUTION_MODE",
		"PORT",
		"NVOKEN_PUBLIC_BASE_URL",
		"NVOKEN_TRUST_FORWARDED_CLIENT_IP",
		"DATABASE_URL",
		"DATABASE_MAX_CONNS",
		"RUNTIME_API_KEY",
		"NVOKEN_API_KEY",
		"NVOKEN_BASE_URL",
		"NVOKEN_PROVIDER",
		"NVOKEN_MODEL",
		"BOOTSTRAP_OWNER_SECRET",
		"CREDENTIAL_DELIVERY_KEY",
		"MODEL_CREDENTIAL_DEPLOYMENT_MODE",
		"INVOCATION_DEFAULT_CREDENTIAL_SOURCE",
		"ANTHROPIC_API_KEY",
		"OPENAI_API_KEY",
		"ENGINE_CONCURRENCY",
		"SHUTDOWN_TIMEOUT",
		"ENGINE_DRAIN_GRACE",
	}
	var content strings.Builder
	content.WriteString(fileMarker)
	content.WriteString("\n")
	for _, name := range order {
		_, _ = fmt.Fprintf(&content, "%s=%s\n", name, values[name])
	}
	return content.String()
}

func parseExisting(content []byte) (string, map[string]string, error) {
	text := string(content)
	if !strings.HasPrefix(text, fileMarker+"\n") {
		return "", nil, errors.New("refusing to reuse the environment file because nvokend quickstart did not create it")
	}
	values := environmentMap(strings.Split(text, "\n"))
	provider := ""
	for candidate, variable := range providerVariables {
		if values[variable] == "" {
			continue
		}
		if provider != "" {
			return "", nil, errors.New("quickstart .env contains more than one provider key")
		}
		provider = candidate
	}
	if provider == "" || values["RUNTIME_API_KEY"] == "" || values["DATABASE_URL"] == "" ||
		values["NVOKEN_MODEL"] == "" {
		return "", nil, errors.New("quickstart .env is incomplete; remove it and run the command again")
	}
	if values["NVOKEN_API_KEY"] == "" || values["NVOKEN_API_KEY"] != values["RUNTIME_API_KEY"] {
		return "", nil, errors.New("quickstart .env is inconsistent; NVOKEN_API_KEY must match RUNTIME_API_KEY; remove it and run the command again")
	}
	return provider, values, nil
}

func postgresStartError(action string, err error) error {
	message := strings.ToLower(err.Error())
	if strings.Contains(message, "port is already allocated") || strings.Contains(message, "address already in use") {
		return errors.New("localhost port 55432 is already in use; stop the process or container using it and run nvokend quickstart again")
	}
	return fmt.Errorf("%s disposable PostgreSQL 17: %w", action, err)
}

func ensurePostgres(ctx context.Context, docker DockerRunner) error {
	if _, err := docker(ctx, "version", "--format", "{{.Server.Version}}"); err != nil {
		return fmt.Errorf("Docker is required for the local quickstart: %w", err)
	}
	state, inspectErr := docker(
		ctx,
		"inspect",
		"--format",
		`{{ index .Config.Labels "`+containerLabel+`" }}|{{.State.Status}}`,
		containerName,
	)
	if inspectErr != nil {
		if !containerMissing(inspectErr) {
			return fmt.Errorf("inspect disposable PostgreSQL container: %w", inspectErr)
		}
		if _, err := docker(
			ctx,
			"run",
			"--detach",
			"--name",
			containerName,
			"--label",
			containerLabel+"=true",
			"--publish",
			"127.0.0.1:55432:5432",
			"--env",
			"POSTGRES_DB=nvoken",
			"--env",
			"POSTGRES_PASSWORD=nvoken-local",
			"--env",
			"POSTGRES_USER=nvoken",
			"--health-cmd",
			"pg_isready --username=nvoken --dbname=nvoken",
			"--health-interval",
			"1s",
			"--health-timeout",
			"5s",
			"--health-retries",
			"30",
			containerImage,
		); err != nil {
			return postgresStartError("start", err)
		}
	} else {
		label, status, ok := strings.Cut(strings.TrimSpace(state), "|")
		if !ok || label != "true" {
			return fmt.Errorf("container %s already exists and nvoken did not create it", containerName)
		}
		switch status {
		case "running":
		case "created", "exited":
			if _, err := docker(ctx, "start", containerName); err != nil {
				return postgresStartError("restart", err)
			}
		default:
			return fmt.Errorf("container %s has unsupported state %s", containerName, status)
		}
	}

	deadline := time.Now().Add(30 * time.Second)
	for {
		status, err := docker(ctx, "inspect", "--format", "{{.State.Health.Status}}", containerName)
		if err != nil {
			return fmt.Errorf("inspect disposable PostgreSQL health: %w", err)
		}
		switch strings.TrimSpace(status) {
		case "healthy":
			return nil
		case "unhealthy":
			return errors.New("disposable PostgreSQL failed its health check")
		}
		if time.Now().After(deadline) {
			return errors.New("timed out waiting for disposable PostgreSQL 17")
		}
		timer := time.NewTimer(500 * time.Millisecond)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
	}
}
