/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline and callback client tools, structured output, and reusable model provider credential lifecycle are included. Spec references and general administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_model_pricing_capability`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetModelPricingCapabilityError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status429(models::ErrorResponse),
    Status500(models::ErrorResponse),
    Status503(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// Reports whether this nvoken installation's embedded pricing registry has standard USD pricing for the exact provider and model ID. This is a local guardrail capability check only: it does not call the provider, verify provider-account access, or guarantee that a provider response will identify the same served model and include usable token evidence.  `priced` means the exact requested model has a standard USD entry. `unpriced` means the local registry can determine that it has no standard USD entry, so a cost-capped Invocation will fail before a provider call. `unknown` means the active adapter cannot decide before execution; capped work can fail closed after normalized response evidence is available.
pub async fn get_model_pricing_capability(
    configuration: &configuration::Configuration,
    provider: models::ModelProvider,
    model: &str,
) -> Result<models::ModelPricingCapability, Error<GetModelPricingCapabilityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_provider = provider;
    let p_query_model = model;

    let uri_str = format!("{}/v1/model-pricing-capabilities", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("provider", &p_query_provider.to_string())]);
    req_builder = req_builder.query(&[("model", &p_query_model.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ModelPricingCapability`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ModelPricingCapability`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetModelPricingCapabilityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
