/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline client tools, callback tools, and structured output are included. Spec references and administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallbackToolSpec {
    /// Unique within the spec; the `nvoken_` prefix is reserved.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "mode", deserialize_with = "Option::deserialize")]
    pub mode: Option<serde_json::Value>,
    /// Object-root JSON Schema using the same bounded, self-contained subset as structured output. Compact canonical JSON is limited to 32 KiB.
    #[serde(rename = "input_schema")]
    pub input_schema: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "callback")]
    pub callback: Box<models::CallbackTarget>,
}

impl CallbackToolSpec {
    pub fn new(
        name: String,
        description: String,
        mode: Option<serde_json::Value>,
        input_schema: std::collections::HashMap<String, serde_json::Value>,
        callback: models::CallbackTarget,
    ) -> CallbackToolSpec {
        CallbackToolSpec {
            name,
            description,
            mode,
            input_schema,
            callback: Box::new(callback),
        }
    }
}
