/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline and callback host tools, structured output, and reusable model provider credential lifecycle are included. Spec references and general administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "unauthenticated")]
    Unauthenticated,
    #[serde(rename = "forbidden")]
    Forbidden,
    #[serde(rename = "not_found")]
    NotFound,
    #[serde(rename = "idempotency_conflict")]
    IdempotencyConflict,
    #[serde(rename = "provider_credential_conflict")]
    ProviderCredentialConflict,
    #[serde(rename = "session_invocation_active")]
    SessionInvocationActive,
    #[serde(rename = "invocation_not_waiting")]
    InvocationNotWaiting,
    #[serde(rename = "tool_result_conflict")]
    ToolResultConflict,
    #[serde(rename = "tool_result_expired")]
    ToolResultExpired,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "unavailable")]
    Unavailable,
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InvalidRequest => write!(f, "invalid_request"),
            Self::Unauthenticated => write!(f, "unauthenticated"),
            Self::Forbidden => write!(f, "forbidden"),
            Self::NotFound => write!(f, "not_found"),
            Self::IdempotencyConflict => write!(f, "idempotency_conflict"),
            Self::ProviderCredentialConflict => write!(f, "provider_credential_conflict"),
            Self::SessionInvocationActive => write!(f, "session_invocation_active"),
            Self::InvocationNotWaiting => write!(f, "invocation_not_waiting"),
            Self::ToolResultConflict => write!(f, "tool_result_conflict"),
            Self::ToolResultExpired => write!(f, "tool_result_expired"),
            Self::RateLimited => write!(f, "rate_limited"),
            Self::Internal => write!(f, "internal"),
            Self::Unavailable => write!(f, "unavailable"),
        }
    }
}

impl Default for ErrorCode {
    fn default() -> ErrorCode {
        Self::InvalidRequest
    }
}
