/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline and callback host tools, structured output, and reusable model provider credential lifecycle are included. Spec references and general administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvocationStreamEvent : Typed event from one Invocation stream. A minimal consumer prints `output_text.delta` and finishes on `invocation.result`.
/// Typed event from one Invocation stream. A minimal consumer prints `output_text.delta` and finishes on `invocation.result`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InvocationStreamEvent {
    InvocationAcceptedEvent(Box<models::InvocationAcceptedEvent>),
    OutputTextDeltaEvent(Box<models::OutputTextDeltaEvent>),
    ThinkingDeltaEvent(Box<models::ThinkingDeltaEvent>),
    InvocationUpdateEvent(Box<models::InvocationUpdateEvent>),
    InvocationResultEvent(Box<models::InvocationResultEvent>),
    StreamResyncEvent(Box<models::StreamResyncEvent>),
    StreamEndEvent(Box<models::StreamEndEvent>),
}

impl Default for InvocationStreamEvent {
    fn default() -> Self {
        Self::InvocationAcceptedEvent(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "invocation.accepted")]
    EventInvocationAccepted,
    #[serde(rename = "output_text.delta")]
    OutputTextDelta,
    #[serde(rename = "thinking.delta")]
    ThinkingDelta,
    #[serde(rename = "invocation.update")]
    InvocationUpdate,
    #[serde(rename = "invocation.result")]
    InvocationResult,
    #[serde(rename = "stream.resync")]
    StreamResync,
    #[serde(rename = "stream.end")]
    StreamEnd,
}

impl Default for Type {
    fn default() -> Type {
        Self::EventInvocationAccepted
    }
}
/// `rotate` means reconnect with `resume_cursor`. `terminal` means the scoped Invocation settled, or the Session became idle for a Session-scoped stream.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "terminal")]
    Terminal,
    #[serde(rename = "rotate")]
    Rotate,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::Terminal
    }
}
