/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline client tools, callback tools, and structured output are included. Spec references and administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelProvenance {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "requested_model")]
    pub requested_model: String,
    #[serde(rename = "served_model")]
    pub served_model: String,
    #[serde(rename = "credential_source", deserialize_with = "Option::deserialize")]
    pub credential_source: Option<serde_json::Value>,
}

impl ModelProvenance {
    pub fn new(
        provider: String,
        requested_model: String,
        served_model: String,
        credential_source: Option<serde_json::Value>,
    ) -> ModelProvenance {
        ModelProvenance {
            provider,
            requested_model,
            served_model,
            credential_source,
        }
    }
}
