/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline and callback host tools, structured output, and reusable model provider credential lifecycle are included. Spec references and general administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputTextDeltaEvent {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// UUIDv7 with the public `sesn_` prefix.
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// UUIDv7 with the public `invk_` prefix.
    #[serde(rename = "invocation_id")]
    pub invocation_id: String,
    /// Execution attempt that emitted this preview. Discard provisional output from earlier attempts when this value increases.
    #[serde(rename = "attempt")]
    pub attempt: u64,
    /// Model iteration that owns the assistant message.
    #[serde(rename = "iteration")]
    pub iteration: u32,
    #[serde(rename = "content_index")]
    pub content_index: u32,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "emitted_at")]
    pub emitted_at: chrono::DateTime<chrono::FixedOffset>,
}

impl OutputTextDeltaEvent {
    pub fn new(
        r#type: Type,
        session_id: String,
        invocation_id: String,
        attempt: u64,
        iteration: u32,
        content_index: u32,
        text: String,
        emitted_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> OutputTextDeltaEvent {
        OutputTextDeltaEvent {
            r#type,
            session_id,
            invocation_id,
            attempt,
            iteration,
            content_index,
            text,
            emitted_at,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "output_text.delta")]
    EventOutputTextDelta,
}

impl Default for Type {
    fn default() -> Type {
        Self::EventOutputTextDelta
    }
}
