/*
 * nvoken Runtime API
 *
 * This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline and callback client tools, structured output, and reusable model provider credential lifecycle are included. Spec references and general administrative APIs remain outside this version.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    /// UUIDv7 with the public `sesn_` prefix.
    #[serde(rename = "id")]
    pub id: String,
    /// UUIDv7 with the public `agnt_` prefix.
    #[serde(rename = "agent_id")]
    pub agent_id: String,
    /// Immutable effective tenant partition reference.
    #[serde(rename = "tenant_ref", deserialize_with = "Option::deserialize")]
    pub tenant_ref: Option<String>,
    #[serde(rename = "session_key", deserialize_with = "Option::deserialize")]
    pub session_key: Option<String>,
    /// The queued, running, or waiting Invocation, if one exists.
    #[serde(
        rename = "active_invocation_id",
        deserialize_with = "Option::deserialize"
    )]
    pub active_invocation_id: Option<String>,
    /// Status of active_invocation_id; null exactly when that ID is null.
    #[serde(
        rename = "active_invocation_status",
        deserialize_with = "Option::deserialize"
    )]
    pub active_invocation_status: Option<ActiveInvocationStatus>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Pending client calls for the active waiting Invocation.
    #[serde(rename = "pending_tool_calls", skip_serializing_if = "Option::is_none")]
    pub pending_tool_calls: Option<Vec<models::PendingClientToolCall>>,
}

impl Session {
    pub fn new(
        id: String,
        agent_id: String,
        tenant_ref: Option<String>,
        session_key: Option<String>,
        active_invocation_id: Option<String>,
        active_invocation_status: Option<ActiveInvocationStatus>,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> Session {
        Session {
            id,
            agent_id,
            tenant_ref,
            session_key,
            active_invocation_id,
            active_invocation_status,
            created_at,
            updated_at,
            pending_tool_calls: None,
        }
    }
}
/// Status of active_invocation_id; null exactly when that ID is null.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActiveInvocationStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting")]
    Waiting,
}

impl Default for ActiveInvocationStatus {
    fn default() -> ActiveInvocationStatus {
        Self::Queued
    }
}
