/* tslint:disable */
/* eslint-disable */
/**
 * nvoken Identity API
 * Durable machine API key contract. Machine credentials use `nvk_…` bearer API keys. A configured trusted console may also present a short-lived Ed25519 issuer token; this is an authentication presentation only and does not create a user identity model in nvoken.  Authorization matrix: - Runtime credentials may call every Runtime operation and GET /v1/identity. - Viewer credentials may call Runtime reads and GET /v1/identity. - Operator credentials may call every Runtime operation, GET /v1/identity, and all credential lifecycle operations. Tenant, Session, operation, and expiry constraints only narrow these grants.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CurrentIdentityAuthentication } from './CurrentIdentityAuthentication.js';
import {
    CurrentIdentityAuthenticationFromJSON,
    CurrentIdentityAuthenticationFromJSONTyped,
    CurrentIdentityAuthenticationToJSON,
    CurrentIdentityAuthenticationToJSONTyped,
} from './CurrentIdentityAuthentication.js';

/**
 *
 * @export
 * @interface CurrentIdentity
 */
export interface CurrentIdentity {
    /**
     *
     * @type {CurrentIdentityAuthentication}
     * @memberof CurrentIdentity
     */
    authentication: CurrentIdentityAuthentication;
}

/**
 * Check if a given object implements the CurrentIdentity interface.
 */
export function instanceOfCurrentIdentity(value: object): value is CurrentIdentity {
    if (!('authentication' in value) || value['authentication'] === undefined) return false;
    return true;
}

export function CurrentIdentityFromJSON(json: any): CurrentIdentity {
    return CurrentIdentityFromJSONTyped(json, false);
}

export function CurrentIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentIdentity {
    if (json == null) {
        return json;
    }
    return {

        'authentication': CurrentIdentityAuthenticationFromJSON(json['authentication']),
    };
}

export function CurrentIdentityToJSON(json: any): CurrentIdentity {
    return CurrentIdentityToJSONTyped(json, false);
}

export function CurrentIdentityToJSONTyped(value?: CurrentIdentity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'authentication': CurrentIdentityAuthenticationToJSON(value['authentication']),
    };
}
