/* tslint:disable */
/* eslint-disable */
/**
 * nvoken Identity API
 * Durable machine API key contract. Machine credentials use `nvk_…` bearer API keys. A configured trusted console may also present a short-lived Ed25519 issuer token; this is an authentication presentation only and does not create a user identity model in nvoken.  Authorization matrix: - Runtime credentials may call every Runtime operation and GET /v1/identity. - Viewer credentials may call Runtime reads and GET /v1/identity. - Operator credentials may call every Runtime operation, GET /v1/identity, and all credential lifecycle operations. Tenant, Session, operation, and expiry constraints only narrow these grants.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 *
 * @export
 * @interface RotateCredentialRequest
 */
export interface RotateCredentialRequest {
    /**
     *
     * @type {number}
     * @memberof RotateCredentialRequest
     */
    overlapSeconds: number;
}

/**
 * Check if a given object implements the RotateCredentialRequest interface.
 */
export function instanceOfRotateCredentialRequest(value: object): value is RotateCredentialRequest {
    if (!('overlapSeconds' in value) || value['overlapSeconds'] === undefined) return false;
    return true;
}

export function RotateCredentialRequestFromJSON(json: any): RotateCredentialRequest {
    return RotateCredentialRequestFromJSONTyped(json, false);
}

export function RotateCredentialRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateCredentialRequest {
    if (json == null) {
        return json;
    }
    return {

        'overlapSeconds': json['overlap_seconds'],
    };
}

export function RotateCredentialRequestToJSON(json: any): RotateCredentialRequest {
    return RotateCredentialRequestToJSONTyped(json, false);
}

export function RotateCredentialRequestToJSONTyped(value?: RotateCredentialRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'overlap_seconds': value['overlapSeconds'],
    };
}
