// Package identitygenerated provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identitygenerated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CredentialStatus.
const (
	Active  CredentialStatus = "active"
	Revoked CredentialStatus = "revoked"
)

// Valid indicates whether the value is a known member of the CredentialStatus enum.
func (e CredentialStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for CurrentIdentityAuthenticationAssurance.
const (
	Bearer CurrentIdentityAuthenticationAssurance = "bearer"
)

// Valid indicates whether the value is a known member of the CurrentIdentityAuthenticationAssurance enum.
func (e CurrentIdentityAuthenticationAssurance) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for CurrentIdentityAuthenticationMethod.
const (
	APIKey      CurrentIdentityAuthenticationMethod = "api_key"
	IssuerToken CurrentIdentityAuthenticationMethod = "issuer_token"
)

// Valid indicates whether the value is a known member of the CurrentIdentityAuthenticationMethod enum.
func (e CurrentIdentityAuthenticationMethod) Valid() bool {
	switch e {
	case APIKey:
		return true
	case IssuerToken:
		return true
	default:
		return false
	}
}

// Defines values for Operation.
const (
	CancelInvocation     Operation = "cancel_invocation"
	CreateCredential     Operation = "create_credential"
	CreateInvocation     Operation = "create_invocation"
	CreateProviderKey    Operation = "create_provider_key"
	CreateSession        Operation = "create_session"
	DeleteSession        Operation = "delete_session"
	GetAgent             Operation = "get_agent"
	GetApp               Operation = "get_app"
	GetCredential        Operation = "get_credential"
	GetIdentity          Operation = "get_identity"
	GetInvocation        Operation = "get_invocation"
	GetProviderKey       Operation = "get_provider_key"
	GetSession           Operation = "get_session"
	GetSessionTranscript Operation = "get_session_transcript"
	ListAgents           Operation = "list_agents"
	ListApps             Operation = "list_apps"
	ListCredentials      Operation = "list_credentials"
	ListInvocations      Operation = "list_invocations"
	ListProviderKeys     Operation = "list_provider_keys"
	ListSessionMessages  Operation = "list_session_messages"
	ListSessions         Operation = "list_sessions"
	ReadBudgets          Operation = "read_budgets"
	ReadUsage            Operation = "read_usage"
	RegisterApp          Operation = "register_app"
	ResumeInvocation     Operation = "resume_invocation"
	RevokeCredential     Operation = "revoke_credential"
	RevokeProviderKey    Operation = "revoke_provider_key"
	RotateCredential     Operation = "rotate_credential"
	RotateProviderKey    Operation = "rotate_provider_key"
	SubmitToolResults    Operation = "submit_tool_results"
	UpdateApp            Operation = "update_app"
	UpdateSession        Operation = "update_session"
	WriteBudgets         Operation = "write_budgets"
)

// Valid indicates whether the value is a known member of the Operation enum.
func (e Operation) Valid() bool {
	switch e {
	case CancelInvocation:
		return true
	case CreateCredential:
		return true
	case CreateInvocation:
		return true
	case CreateProviderKey:
		return true
	case CreateSession:
		return true
	case DeleteSession:
		return true
	case GetAgent:
		return true
	case GetApp:
		return true
	case GetCredential:
		return true
	case GetIdentity:
		return true
	case GetInvocation:
		return true
	case GetProviderKey:
		return true
	case GetSession:
		return true
	case GetSessionTranscript:
		return true
	case ListAgents:
		return true
	case ListApps:
		return true
	case ListCredentials:
		return true
	case ListInvocations:
		return true
	case ListProviderKeys:
		return true
	case ListSessionMessages:
		return true
	case ListSessions:
		return true
	case ReadBudgets:
		return true
	case ReadUsage:
		return true
	case RegisterApp:
		return true
	case ResumeInvocation:
		return true
	case RevokeCredential:
		return true
	case RevokeProviderKey:
		return true
	case RotateCredential:
		return true
	case RotateProviderKey:
		return true
	case SubmitToolResults:
		return true
	case UpdateApp:
		return true
	case UpdateSession:
		return true
	case WriteBudgets:
		return true
	default:
		return false
	}
}

// Defines values for Profile.
const (
	Operator Profile = "Operator"
	Runtime  Profile = "Runtime"
	Viewer   Profile = "Viewer"
)

// Valid indicates whether the value is a known member of the Profile enum.
func (e Profile) Valid() bool {
	switch e {
	case Operator:
		return true
	case Runtime:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// CreateCredentialRequest defines model for CreateCredentialRequest.
type CreateCredentialRequest struct {
	// AppID Target App for an app-less Operator provisioning an app credential.
	// Omit to issue another app-less credential. An app-bound Operator
	// may omit this field or repeat its own App ID, but cannot name a
	// different App.
	AppID      *string      `json:"app_id,omitempty"`
	ExpiresAt  *time.Time   `json:"expires_at,omitempty"`
	Name       string       `json:"name"`
	Operations *[]Operation `json:"operations,omitempty"`
	Profile    Profile      `json:"profile"`
	SessionID  *string      `json:"session_id,omitempty"`
	TenantKey  *string      `json:"tenant_key,omitempty"`
}

// Credential defines model for Credential.
type Credential struct {
	AppID               *string   `json:"app_id,omitempty"`
	CreatedAt           time.Time `json:"created_at"`
	CreatorCredentialID *string   `json:"creator_credential_id,omitempty"`

	// CreatorSubject Opaque issuer subject when the credential was created by an issuer token.
	CreatorSubject        *string          `json:"creator_subject,omitempty"`
	ExpiresAt             *time.Time       `json:"expires_at,omitempty"`
	ID                    string           `json:"id"`
	LastUsedAt            *time.Time       `json:"last_used_at,omitempty"`
	Name                  string           `json:"name"`
	Operations            []Operation      `json:"operations"`
	Prefix                string           `json:"prefix"`
	Profile               Profile          `json:"profile"`
	RevokedAt             *time.Time       `json:"revoked_at,omitempty"`
	RotatedFromID         *string          `json:"rotated_from_id,omitempty"`
	RotationOverlapEndsAt *time.Time       `json:"rotation_overlap_ends_at,omitempty"`
	SessionID             *string          `json:"session_id,omitempty"`
	Status                CredentialStatus `json:"status"`
	TenantKey             *string          `json:"tenant_key,omitempty"`
	UpdatedAt             time.Time        `json:"updated_at"`
}

// CredentialIssuance defines model for CredentialIssuance.
type CredentialIssuance struct {
	Credential        Credential `json:"credential"`
	DeliveryExpiresAt time.Time  `json:"delivery_expires_at"`
	Replayed          bool       `json:"replayed"`
	Secret            *string    `json:"secret,omitempty"`
}

// CredentialList defines model for CredentialList.
type CredentialList struct {
	HasMore    bool         `json:"has_more"`
	Items      []Credential `json:"items"`
	NextCursor *string      `json:"next_cursor"`
}

// CredentialStatus defines model for CredentialStatus.
type CredentialStatus string

// CurrentIdentity defines model for CurrentIdentity.
type CurrentIdentity struct {
	Authentication struct {
		Assurance        CurrentIdentityAuthenticationAssurance `json:"assurance"`
		CredentialID     string                                 `json:"credential_id"`
		EffectiveProfile Profile                                `json:"effective_profile"`
		Method           CurrentIdentityAuthenticationMethod    `json:"method"`
		Operations       []Operation                            `json:"operations"`
		SessionID        *string                                `json:"session_id,omitempty"`
		TenantKey        *string                                `json:"tenant_key,omitempty"`
	} `json:"authentication"`
}

// CurrentIdentityAuthenticationAssurance defines model for CurrentIdentity.Authentication.Assurance.
type CurrentIdentityAuthenticationAssurance string

// CurrentIdentityAuthenticationMethod defines model for CurrentIdentity.Authentication.Method.
type CurrentIdentityAuthenticationMethod string

// Error defines model for Error.
type Error struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestID string                  `json:"request_id"`
}

// Operation defines model for Operation.
type Operation string

// Profile defines model for Profile.
type Profile string

// CredentialID defines model for CredentialID.
type CredentialID = string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = Error

// ListCredentialsParams defines parameters for ListCredentials.
type ListCredentialsParams struct {
	Status *CredentialStatus `form:"status,omitempty" json:"status,omitempty"`

	// Cursor Opaque continuation cursor bound to the status filter and page limit.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum credentials in this page. Defaults to 100.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateCredentialParams defines parameters for CreateCredential.
type CreateCredentialParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RotateCredentialJSONBody defines parameters for RotateCredential.
type RotateCredentialJSONBody struct {
	OverlapSeconds int `json:"overlap_seconds"`
}

// RotateCredentialParams defines parameters for RotateCredential.
type RotateCredentialParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateCredentialJSONRequestBody defines body for CreateCredential for application/json ContentType.
type CreateCredentialJSONRequestBody = CreateCredentialRequest

// RotateCredentialJSONRequestBody defines body for RotateCredential for application/json ContentType.
type RotateCredentialJSONRequestBody RotateCredentialJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCurrentIdentity Explain the authenticated caller
	//
	// Corresponds with GET /v1/identity (the `GetCurrentIdentity` operationId).
	GetCurrentIdentity(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCredentials List safe credential metadata
	//
	// Corresponds with GET /v1/identity/credentials (the `ListCredentials` operationId).
	ListCredentials(ctx context.Context, params *ListCredentialsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCredentialWithBody Create a machine credential
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
	CreateCredentialWithBody(ctx context.Context, params *CreateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCredential Create a machine credential
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
	CreateCredential(ctx context.Context, params *CreateCredentialParams, body CreateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCredential Read safe credential metadata
	//
	// Corresponds with GET /v1/identity/credentials/{credential_id} (the `GetCredential` operationId).
	GetCredential(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeCredential Revoke a credential
	//
	// Corresponds with POST /v1/identity/credentials/{credential_id}/revoke (the `RevokeCredential` operationId).
	RevokeCredential(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RotateCredentialWithBody Rotate a machine credential with bounded overlap
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
	RotateCredentialWithBody(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RotateCredential Rotate a machine credential with bounded overlap
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
	RotateCredential(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, body RotateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCurrentIdentity Explain the authenticated caller
//
// Corresponds with GET /v1/identity (the `GetCurrentIdentity` operationId).
func (c *Client) GetCurrentIdentity(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCurrentIdentityRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListCredentials List safe credential metadata
//
// Corresponds with GET /v1/identity/credentials (the `ListCredentials` operationId).
func (c *Client) ListCredentials(ctx context.Context, params *ListCredentialsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCredentialsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCredentialWithBody Create a machine credential
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
func (c *Client) CreateCredentialWithBody(ctx context.Context, params *CreateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCredentialRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCredential Create a machine credential
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
func (c *Client) CreateCredential(ctx context.Context, params *CreateCredentialParams, body CreateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCredentialRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCredential Read safe credential metadata
//
// Corresponds with GET /v1/identity/credentials/{credential_id} (the `GetCredential` operationId).
func (c *Client) GetCredential(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCredentialRequest(c.Server, credentialID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RevokeCredential Revoke a credential
//
// Corresponds with POST /v1/identity/credentials/{credential_id}/revoke (the `RevokeCredential` operationId).
func (c *Client) RevokeCredential(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeCredentialRequest(c.Server, credentialID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RotateCredentialWithBody Rotate a machine credential with bounded overlap
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
func (c *Client) RotateCredentialWithBody(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRotateCredentialRequestWithBody(c.Server, credentialID, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RotateCredential Rotate a machine credential with bounded overlap
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
func (c *Client) RotateCredential(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, body RotateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRotateCredentialRequest(c.Server, credentialID, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCurrentIdentityRequest constructs an http.Request for the GetCurrentIdentity method
func NewGetCurrentIdentityRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/identity")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCredentialsRequest constructs an http.Request for the ListCredentials method
func NewListCredentialsRequest(server string, params *ListCredentialsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/identity/credentials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCredentialRequest calls the generic CreateCredential builder with application/json body
func NewCreateCredentialRequest(server string, params *CreateCredentialParams, body CreateCredentialJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCredentialRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateCredentialRequestWithBody constructs an http.Request for the CreateCredential method, with any body, and a specified content type
func NewCreateCredentialRequestWithBody(server string, params *CreateCredentialParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/identity/credentials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewGetCredentialRequest constructs an http.Request for the GetCredential method
func NewGetCredentialRequest(server string, credentialID CredentialID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "credential_id", credentialID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/identity/credentials/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeCredentialRequest constructs an http.Request for the RevokeCredential method
func NewRevokeCredentialRequest(server string, credentialID CredentialID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "credential_id", credentialID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/identity/credentials/%s/revoke", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRotateCredentialRequest calls the generic RotateCredential builder with application/json body
func NewRotateCredentialRequest(server string, credentialID CredentialID, params *RotateCredentialParams, body RotateCredentialJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRotateCredentialRequestWithBody(server, credentialID, params, "application/json", bodyReader)
}

// NewRotateCredentialRequestWithBody constructs an http.Request for the RotateCredential method, with any body, and a specified content type
func NewRotateCredentialRequestWithBody(server string, credentialID CredentialID, params *RotateCredentialParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "credential_id", credentialID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/identity/credentials/%s/rotate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCurrentIdentityWithResponse Explain the authenticated caller
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/identity (the `GetCurrentIdentity` operationId).
	GetCurrentIdentityWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentIdentityHTTPResponse, error)

	// ListCredentialsWithResponse List safe credential metadata
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/identity/credentials (the `ListCredentials` operationId).
	ListCredentialsWithResponse(ctx context.Context, params *ListCredentialsParams, reqEditors ...RequestEditorFn) (*ListCredentialsHTTPResponse, error)

	// CreateCredentialWithBodyWithResponse Create a machine credential
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
	CreateCredentialWithBodyWithResponse(ctx context.Context, params *CreateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCredentialHTTPResponse, error)

	// CreateCredentialWithResponse Create a machine credential
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
	CreateCredentialWithResponse(ctx context.Context, params *CreateCredentialParams, body CreateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCredentialHTTPResponse, error)

	// GetCredentialWithResponse Read safe credential metadata
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/identity/credentials/{credential_id} (the `GetCredential` operationId).
	GetCredentialWithResponse(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*GetCredentialHTTPResponse, error)

	// RevokeCredentialWithResponse Revoke a credential
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/identity/credentials/{credential_id}/revoke (the `RevokeCredential` operationId).
	RevokeCredentialWithResponse(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*RevokeCredentialHTTPResponse, error)

	// RotateCredentialWithBodyWithResponse Rotate a machine credential with bounded overlap
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
	RotateCredentialWithBodyWithResponse(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RotateCredentialHTTPResponse, error)

	// RotateCredentialWithResponse Rotate a machine credential with bounded overlap
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
	RotateCredentialWithResponse(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, body RotateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*RotateCredentialHTTPResponse, error)
}

type GetCurrentIdentityHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CurrentIdentity
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthenticated
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCurrentIdentityHTTPResponse) GetJSON200() *CurrentIdentity {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetCurrentIdentityHTTPResponse) GetJSON401() *Unauthenticated {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r GetCurrentIdentityHTTPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCurrentIdentityHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCurrentIdentityHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCurrentIdentityHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListCredentialsHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CredentialList
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthenticated
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListCredentialsHTTPResponse) GetJSON200() *CredentialList {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListCredentialsHTTPResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListCredentialsHTTPResponse) GetJSON401() *Unauthenticated {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListCredentialsHTTPResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetBody returns the raw response body bytes
func (r ListCredentialsHTTPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListCredentialsHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCredentialsHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListCredentialsHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateCredentialHTTPResponse201Headers the declared response headers of an HTTP 201 response for CreateCredential
type CreateCredentialHTTPResponse201Headers struct {
	CacheControl *string
}

type CreateCredentialHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *CredentialIssuance
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthenticated
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// Headers201 the parsed response headers for an HTTP 201 response
	Headers201 *CreateCredentialHTTPResponse201Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateCredentialHTTPResponse) GetJSON201() *CredentialIssuance {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateCredentialHTTPResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateCredentialHTTPResponse) GetJSON401() *Unauthenticated {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreateCredentialHTTPResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateCredentialHTTPResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r CreateCredentialHTTPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateCredentialHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCredentialHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateCredentialHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCredentialHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Credential
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthenticated
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCredentialHTTPResponse) GetJSON200() *Credential {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetCredentialHTTPResponse) GetJSON401() *Unauthenticated {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetCredentialHTTPResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetCredentialHTTPResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetCredentialHTTPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCredentialHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCredentialHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCredentialHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeCredentialHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Credential
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthenticated
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RevokeCredentialHTTPResponse) GetJSON200() *Credential {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r RevokeCredentialHTTPResponse) GetJSON401() *Unauthenticated {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r RevokeCredentialHTTPResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r RevokeCredentialHTTPResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r RevokeCredentialHTTPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RevokeCredentialHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeCredentialHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeCredentialHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RotateCredentialHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *CredentialIssuance
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *InvalidRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthenticated
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r RotateCredentialHTTPResponse) GetJSON201() *CredentialIssuance {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r RotateCredentialHTTPResponse) GetJSON400() *InvalidRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r RotateCredentialHTTPResponse) GetJSON401() *Unauthenticated {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r RotateCredentialHTTPResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r RotateCredentialHTTPResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r RotateCredentialHTTPResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r RotateCredentialHTTPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RotateCredentialHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RotateCredentialHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RotateCredentialHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCurrentIdentityWithResponse Explain the authenticated caller
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/identity (the `GetCurrentIdentity` operationId).
func (c *ClientWithResponses) GetCurrentIdentityWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentIdentityHTTPResponse, error) {
	rsp, err := c.GetCurrentIdentity(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCurrentIdentityHTTPResponse(rsp)
}

// ListCredentialsWithResponse List safe credential metadata
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/identity/credentials (the `ListCredentials` operationId).
func (c *ClientWithResponses) ListCredentialsWithResponse(ctx context.Context, params *ListCredentialsParams, reqEditors ...RequestEditorFn) (*ListCredentialsHTTPResponse, error) {
	rsp, err := c.ListCredentials(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCredentialsHTTPResponse(rsp)
}

// CreateCredentialWithBodyWithResponse Create a machine credential
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
func (c *ClientWithResponses) CreateCredentialWithBodyWithResponse(ctx context.Context, params *CreateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCredentialHTTPResponse, error) {
	rsp, err := c.CreateCredentialWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCredentialHTTPResponse(rsp)
}

// CreateCredentialWithResponse Create a machine credential
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/identity/credentials (the `CreateCredential` operationId).
func (c *ClientWithResponses) CreateCredentialWithResponse(ctx context.Context, params *CreateCredentialParams, body CreateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCredentialHTTPResponse, error) {
	rsp, err := c.CreateCredential(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCredentialHTTPResponse(rsp)
}

// GetCredentialWithResponse Read safe credential metadata
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/identity/credentials/{credential_id} (the `GetCredential` operationId).
func (c *ClientWithResponses) GetCredentialWithResponse(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*GetCredentialHTTPResponse, error) {
	rsp, err := c.GetCredential(ctx, credentialID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCredentialHTTPResponse(rsp)
}

// RevokeCredentialWithResponse Revoke a credential
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/identity/credentials/{credential_id}/revoke (the `RevokeCredential` operationId).
func (c *ClientWithResponses) RevokeCredentialWithResponse(ctx context.Context, credentialID CredentialID, reqEditors ...RequestEditorFn) (*RevokeCredentialHTTPResponse, error) {
	rsp, err := c.RevokeCredential(ctx, credentialID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeCredentialHTTPResponse(rsp)
}

// RotateCredentialWithBodyWithResponse Rotate a machine credential with bounded overlap
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
func (c *ClientWithResponses) RotateCredentialWithBodyWithResponse(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RotateCredentialHTTPResponse, error) {
	rsp, err := c.RotateCredentialWithBody(ctx, credentialID, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRotateCredentialHTTPResponse(rsp)
}

// RotateCredentialWithResponse Rotate a machine credential with bounded overlap
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/identity/credentials/{credential_id}/rotate (the `RotateCredential` operationId).
func (c *ClientWithResponses) RotateCredentialWithResponse(ctx context.Context, credentialID CredentialID, params *RotateCredentialParams, body RotateCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*RotateCredentialHTTPResponse, error) {
	rsp, err := c.RotateCredential(ctx, credentialID, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRotateCredentialHTTPResponse(rsp)
}

// ParseGetCurrentIdentityHTTPResponse parses an HTTP response from a GetCurrentIdentityWithResponse call
func ParseGetCurrentIdentityHTTPResponse(rsp *http.Response) (*GetCurrentIdentityHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCurrentIdentityHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CurrentIdentity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListCredentialsHTTPResponse parses an HTTP response from a ListCredentialsWithResponse call
func ParseListCredentialsHTTPResponse(rsp *http.Response) (*ListCredentialsHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCredentialsHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CredentialList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseCreateCredentialHTTPResponse parses an HTTP response from a CreateCredentialWithResponse call
func ParseCreateCredentialHTTPResponse(rsp *http.Response) (*CreateCredentialHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCredentialHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CredentialIssuance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	switch {
	case rsp.StatusCode == 201:
		var headers CreateCredentialHTTPResponse201Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers201 = &headers
	}

	return response, nil
}

// ParseGetCredentialHTTPResponse parses an HTTP response from a GetCredentialWithResponse call
func ParseGetCredentialHTTPResponse(rsp *http.Response) (*GetCredentialHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCredentialHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Credential
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRevokeCredentialHTTPResponse parses an HTTP response from a RevokeCredentialWithResponse call
func ParseRevokeCredentialHTTPResponse(rsp *http.Response) (*RevokeCredentialHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeCredentialHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Credential
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRotateCredentialHTTPResponse parses an HTTP response from a RotateCredentialWithResponse call
func ParseRotateCredentialHTTPResponse(rsp *http.Response) (*RotateCredentialHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RotateCredentialHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CredentialIssuance
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvalidRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
