# coding: utf-8

# flake8: noqa
"""
    nvoken API

    nvoken runs agent turns for you. You describe a turn — an Agent Definition and some input — and nvoken queues it, runs it in the background, keeps running it across restarts and failures, and lets you either watch it live or come back for the result later.  Your application stays in charge of what your agents are and when they run. nvoken owns the conversation: it stores the messages, tracks the state of every turn, and handles talking to the model providers.  ## Getting started  `POST /v1/invocations` starts a turn and returns a `202` right away. From there:  - Follow it live with `GET /v1/invocations/{invocation_id}/stream`, or   read `GET /v1/invocations/{invocation_id}/result` whenever you want the   finished answer. Disconnecting never cancels anything. - If your agent uses tools you run yourself, the turn stops with status   `waiting` and lists what it needs. Run them, post the results to   `/tool-results`, and the turn continues where it left off. - Sessions carry conversation history from one turn to the next. They   last until you delete them, or until a retention window you set runs   out.  Also here: tools nvoken calls back to over HTTPS, remote MCP servers, structured output validated against your JSON Schema, reusable Agent Definitions, image and document input, your own model provider keys, and spending limits.  ## Authorization  Machine credentials use `nvk_…` bearer API keys. A configured trusted console may also present a short-lived Ed25519 issuer token; this is an authentication presentation only and does not create a user identity model in nvoken.  Browser-direct callers use narrow JWTs, exact-origin CORS, and App/tenant/user admission limits. A host may mint client tokens from its own Ed25519 key. An App that explicitly enables anonymous access may instead let nvoken mint a short-lived access token and renewable visitor token from one allowed public origin.  A browser grant sees less, and it sees it in the same shape. There is one schema per resource, and the fields a browser may not see are simply omitted from its responses, which is why those fields are not required. There are no parallel browser schemas and no response unions, so every payload decodes against one type and nothing about the shape has to be inferred from the credential that fetched it. `GET /v1/identity` reports which kind of caller you are, under `authentication.method`.  - App-scoped Runtime credentials may call every Runtime operation and GET /v1/identity. - App-scoped Viewer credentials may call Runtime reads and GET /v1/identity. - App-scoped Operator credentials may call every Runtime operation, GET /v1/identity, and all credential lifecycle operations. - Org-scoped Viewer and Operator credentials are management and reporting   identities only. They resolve no tenant and cannot perform Runtime   operations; Operators can register and manage Apps and their App   credentials, while Viewers have read-only access.  Tenant, Session, operation, and expiry constraints only narrow these grants.  ## Familiar names  Where a name already means something in other agent APIs, nvoken uses it the same way rather than inventing its own. `metadata` follows OpenAI's limits of 16 keys, 64-character names, and 512-byte values. `output_text` is the assistant's text joined into one string. `reasoning.effort` takes `low`, `medium`, `high`, `xhigh`, and `max`. `stop_reason: end_turn`, status `running`, and the `commentary` and `final_answer` message phases are the same idea you have seen elsewhere. If you have integrated another agent API, these should need no translation.  ## You can always read back what applied  Anything nvoken decides on your behalf is readable on the resource that used it. You never have to work out what happened by combining the request you sent with your own assumptions about nvoken's defaults — just read the resource.  A turn reports the `limits` it is really running under, after defaults and minimums; the `agent_definition` it ran with, exactly as stored; and `provenance`, which records what actually served the request. A Session reports its compaction (summarization) policy with `auto` already resolved to a real number and a real model, and its retention window as accepted. New settings will work the same way: a default you cannot read back is a setting only the server knows about.  ## Streaming  A turn and an Invocation are the same thing. The endpoint summaries say turn; the schemas say Invocation.  Two streams carry the same frames. `GET /v1/invocations/{invocation_id}/stream` follows one turn and ends when that turn settles. `GET /v1/sessions/{session_id}/transcript/stream` follows every turn in a Session, and is the surface to use for a conversation. `POST /v1/invocations` with `Accept: text/event-stream` admits and streams one turn inline.  ### Saved frames and live frames  Every frame is one or the other, and the difference decides what you may store. A saved frame carries an SSE `id`. That ID is your resume position and the only value you need to keep. A live frame carries no `id`: it is a preview or a control signal, it is never stored, and it is never replayed.  The Invocation stream's saved frames are `invocation.accepted`, `invocation.update`, and `invocation.result`. The Session stream's only saved frame is `transcript.update`. Every other frame on either stream is live.  ### Resuming and finishing  The resume position has one name: `cursor`. It is the field on a durable frame and the query parameter that resumes a stream. Server-Sent Events mirrors it onto the `id:` line and accepts the `Last-Event-ID` header in the parameter's place, because a faithful SSE binding must; those are the binding's mechanics, not two more names for the value, and another binding would carry the same one name. `cursor` wins when a request supplies both. Cursors are Session-scoped on both streams, so a position taken from one stream resumes the other.  Reconnecting to a turn that has already settled always yields `invocation.result` followed by `stream.end` with reason `terminal`, at any cursor. Both are valid signals that a turn is over, and a client may exit on either.  `invocation.accepted` is emitted only by the inline `POST` path. The `GET` stream never sends it, so a client that admits separately never sees it. The nvoken SDKs synthesize an equivalent locally so their callers see the same first event either way.  An `invocation.update` never carries a terminal status. Terminal state arrives as `invocation.result` and nowhere else on that stream. The `invocation` it carries is re-read when the frame is written, so it is current state with a resume position attached rather than a snapshot taken at the cursor.  ### Previews  `output_text.delta` and `thinking.delta` preview one model iteration. Their identity is `(invocation_id, attempt, iteration, content_index)`. Accumulate by that tuple, and discard everything provisional when `attempt` increases, when `stream.resync` arrives, when the saved message lands, and when the turn reaches a terminal status. One model iteration produces exactly one saved assistant message, so previews sharing an `(invocation_id, attempt, iteration)` build one message. Never store preview text as a message, and never use it to decide whether a turn succeeded.  `attempt`, `iteration`, `revision`, and `sequence` count from 1. `content_index` counts from 0.  ### Compatibility  Stream events may gain fields over time. Ignore fields you do not recognize rather than refusing the frame. New enum values may appear too. Treat an unknown `stream.resync` reason as `live_delivery_gap` and discard your previews. Treat an unknown `stream.end` reason as `rotate` and reconnect with your last saved `id`. Reconnecting is always safe: a turn that has settled re-yields its result.  ### Transport  The protocol is the frames and their durability rules. Server-Sent Events is how they travel today and the only binding. Three mechanics belong to SSE itself: the `id:` line, the `retry:` opener, and comment keepalives. Everything else, resumption included, lives in the frames.  ### What the stream carries  Frames carry structure and text. Images and documents travel as descriptors, with media type, size in bytes, and a `sha256:` digest, never as inline bytes. Frame sizes stay bounded by text no matter what a turn produced.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from nvoken_generated.models.activity_metrics import ActivityMetrics
from nvoken_generated.models.admission_attempt import AdmissionAttempt
from nvoken_generated.models.admission_attempt_list import AdmissionAttemptList
from nvoken_generated.models.admission_outcome import AdmissionOutcome
from nvoken_generated.models.admission_reason_count import AdmissionReasonCount
from nvoken_generated.models.admission_summary import AdmissionSummary
from nvoken_generated.models.admission_tenant_count import AdmissionTenantCount
from nvoken_generated.models.agent import Agent
from nvoken_generated.models.agent_definition import AgentDefinition
from nvoken_generated.models.agent_definition_resource import AgentDefinitionResource
from nvoken_generated.models.agent_definition_resource_list import AgentDefinitionResourceList
from nvoken_generated.models.agent_definition_write import AgentDefinitionWrite
from nvoken_generated.models.agent_list import AgentList
from nvoken_generated.models.allocate_credits_request import AllocateCreditsRequest
from nvoken_generated.models.allocate_credits_result import AllocateCreditsResult
from nvoken_generated.models.anonymous_access import AnonymousAccess
from nvoken_generated.models.anonymous_token_request import AnonymousTokenRequest
from nvoken_generated.models.anonymous_token_response import AnonymousTokenResponse
from nvoken_generated.models.app import App
from nvoken_generated.models.app_default_rate_limits import AppDefaultRateLimits
from nvoken_generated.models.app_list import AppList
from nvoken_generated.models.app_registration import AppRegistration
from nvoken_generated.models.app_signing_key_purpose import AppSigningKeyPurpose
from nvoken_generated.models.app_signing_key_secret import AppSigningKeySecret
from nvoken_generated.models.authentication_method import AuthenticationMethod
from nvoken_generated.models.browser_access import BrowserAccess
from nvoken_generated.models.browser_client_interface import BrowserClientInterface
from nvoken_generated.models.browser_invocation_webhook import BrowserInvocationWebhook
from nvoken_generated.models.browser_rate_limits import BrowserRateLimits
from nvoken_generated.models.builtin_tool_declaration import BuiltinToolDeclaration
from nvoken_generated.models.callback_delivery_outcome import CallbackDeliveryOutcome
from nvoken_generated.models.callback_target import CallbackTarget
from nvoken_generated.models.callback_tool_declaration import CallbackToolDeclaration
from nvoken_generated.models.char_location_citation import CharLocationCitation
from nvoken_generated.models.citation import Citation
from nvoken_generated.models.client_key import ClientKey
from nvoken_generated.models.client_key_list import ClientKeyList
from nvoken_generated.models.compaction_policy import CompactionPolicy
from nvoken_generated.models.compaction_policy_trigger_tokens import CompactionPolicyTriggerTokens
from nvoken_generated.models.cost_metrics import CostMetrics
from nvoken_generated.models.create_client_key_request import CreateClientKeyRequest
from nvoken_generated.models.create_credential_request import CreateCredentialRequest
from nvoken_generated.models.create_invocation_request import CreateInvocationRequest
from nvoken_generated.models.create_nudge_request import CreateNudgeRequest
from nvoken_generated.models.create_provider_key_request import CreateProviderKeyRequest
from nvoken_generated.models.create_session_request import CreateSessionRequest
from nvoken_generated.models.credential import Credential
from nvoken_generated.models.credential_issuance import CredentialIssuance
from nvoken_generated.models.credential_list import CredentialList
from nvoken_generated.models.credential_profile import CredentialProfile
from nvoken_generated.models.credential_status import CredentialStatus
from nvoken_generated.models.credit_account import CreditAccount
from nvoken_generated.models.credit_account_list import CreditAccountList
from nvoken_generated.models.credit_allocation import CreditAllocation
from nvoken_generated.models.credit_allocation_list import CreditAllocationList
from nvoken_generated.models.credit_block import CreditBlock
from nvoken_generated.models.credit_policy import CreditPolicy
from nvoken_generated.models.current_identity import CurrentIdentity
from nvoken_generated.models.current_identity_authentication import CurrentIdentityAuthentication
from nvoken_generated.models.document_input_block import DocumentInputBlock
from nvoken_generated.models.document_input_source import DocumentInputSource
from nvoken_generated.models.document_reference_block import DocumentReferenceBlock
from nvoken_generated.models.error_code import ErrorCode
from nvoken_generated.models.error_response import ErrorResponse
from nvoken_generated.models.fork_session_options import ForkSessionOptions
from nvoken_generated.models.fork_session_request import ForkSessionRequest
from nvoken_generated.models.fork_session_request_from_message import ForkSessionRequestFromMessage
from nvoken_generated.models.host_tool_declaration import HostToolDeclaration
from nvoken_generated.models.host_tool_result_acceptance import HostToolResultAcceptance
from nvoken_generated.models.image_input_block import ImageInputBlock
from nvoken_generated.models.image_input_source import ImageInputSource
from nvoken_generated.models.image_reference_block import ImageReferenceBlock
from nvoken_generated.models.input_block import InputBlock
from nvoken_generated.models.invocation import Invocation
from nvoken_generated.models.invocation_accepted_event import InvocationAcceptedEvent
from nvoken_generated.models.invocation_change import InvocationChange
from nvoken_generated.models.invocation_context_item import InvocationContextItem
from nvoken_generated.models.invocation_failure import InvocationFailure
from nvoken_generated.models.invocation_input import InvocationInput
from nvoken_generated.models.invocation_list import InvocationList
from nvoken_generated.models.invocation_log import InvocationLog
from nvoken_generated.models.invocation_log_list import InvocationLogList
from nvoken_generated.models.invocation_result import InvocationResult
from nvoken_generated.models.invocation_result_event import InvocationResultEvent
from nvoken_generated.models.invocation_status import InvocationStatus
from nvoken_generated.models.invocation_stop_reason import InvocationStopReason
from nvoken_generated.models.invocation_stream_event import InvocationStreamEvent
from nvoken_generated.models.invocation_timeline import InvocationTimeline
from nvoken_generated.models.invocation_timeline_step import InvocationTimelineStep
from nvoken_generated.models.invocation_update_event import InvocationUpdateEvent
from nvoken_generated.models.limits import Limits
from nvoken_generated.models.mcp_list_tools_request import MCPListToolsRequest
from nvoken_generated.models.mcp_list_tools_response import MCPListToolsResponse
from nvoken_generated.models.mcp_projected_tool import MCPProjectedTool
from nvoken_generated.models.mcp_server import MCPServer
from nvoken_generated.models.mcp_server_headers import MCPServerHeaders
from nvoken_generated.models.mcp_timeouts import MCPTimeouts
from nvoken_generated.models.mcp_tool_annotations import MCPToolAnnotations
from nvoken_generated.models.mcp_tool_exclusion import MCPToolExclusion
from nvoken_generated.models.memory import Memory
from nvoken_generated.models.memory_config import MemoryConfig
from nvoken_generated.models.memory_context_config import MemoryContextConfig
from nvoken_generated.models.memory_context_mode import MemoryContextMode
from nvoken_generated.models.memory_kind import MemoryKind
from nvoken_generated.models.memory_list import MemoryList
from nvoken_generated.models.memory_search_coverage import MemorySearchCoverage
from nvoken_generated.models.memory_search_mode import MemorySearchMode
from nvoken_generated.models.memory_search_result import MemorySearchResult
from nvoken_generated.models.message_phase import MessagePhase
from nvoken_generated.models.model import Model
from nvoken_generated.models.model_call_fact_status import ModelCallFactStatus
from nvoken_generated.models.model_call_kind import ModelCallKind
from nvoken_generated.models.model_call_record import ModelCallRecord
from nvoken_generated.models.model_control_capabilities import ModelControlCapabilities
from nvoken_generated.models.model_cost import ModelCost
from nvoken_generated.models.model_descriptor import ModelDescriptor
from nvoken_generated.models.model_input import ModelInput
from nvoken_generated.models.model_input_capabilities import ModelInputCapabilities
from nvoken_generated.models.model_list import ModelList
from nvoken_generated.models.model_media_capabilities import ModelMediaCapabilities
from nvoken_generated.models.model_media_kind_capabilities import ModelMediaKindCapabilities
from nvoken_generated.models.model_metrics import ModelMetrics
from nvoken_generated.models.model_pricing import ModelPricing
from nvoken_generated.models.model_provenance import ModelProvenance
from nvoken_generated.models.model_reasoning_budget_capabilities import ModelReasoningBudgetCapabilities
from nvoken_generated.models.model_reasoning_capabilities import ModelReasoningCapabilities
from nvoken_generated.models.model_reasoning_effort_capabilities import ModelReasoningEffortCapabilities
from nvoken_generated.models.model_sampling_capabilities import ModelSamplingCapabilities
from nvoken_generated.models.model_tool_capabilities import ModelToolCapabilities
from nvoken_generated.models.model_tool_choice_capabilities import ModelToolChoiceCapabilities
from nvoken_generated.models.model_tool_choice_mode import ModelToolChoiceMode
from nvoken_generated.models.model_usage import ModelUsage
from nvoken_generated.models.money import Money
from nvoken_generated.models.nudge import Nudge
from nvoken_generated.models.nudge_acknowledgement import NudgeAcknowledgement
from nvoken_generated.models.nudge_list import NudgeList
from nvoken_generated.models.nudge_status import NudgeStatus
from nvoken_generated.models.observation_status import ObservationStatus
from nvoken_generated.models.operation import Operation
from nvoken_generated.models.org import Org
from nvoken_generated.models.org_list import OrgList
from nvoken_generated.models.output_text_delta_event import OutputTextDeltaEvent
from nvoken_generated.models.provider_key import ProviderKey
from nvoken_generated.models.provider_key_list import ProviderKeyList
from nvoken_generated.models.provider_key_scope import ProviderKeyScope
from nvoken_generated.models.provider_key_selection import ProviderKeySelection
from nvoken_generated.models.provider_key_selection_one_of import ProviderKeySelectionOneOf
from nvoken_generated.models.provider_key_selection_one_of1 import ProviderKeySelectionOneOf1
from nvoken_generated.models.provider_key_source import ProviderKeySource
from nvoken_generated.models.provider_key_usage import ProviderKeyUsage
from nvoken_generated.models.provider_static_key import ProviderStaticKey
from nvoken_generated.models.provider_tool import ProviderTool
from nvoken_generated.models.reasoning import Reasoning
from nvoken_generated.models.reasoning_effort import ReasoningEffort
from nvoken_generated.models.redacted_block import RedactedBlock
from nvoken_generated.models.register_app_request import RegisterAppRequest
from nvoken_generated.models.register_org_request import RegisterOrgRequest
from nvoken_generated.models.reminder_block import ReminderBlock
from nvoken_generated.models.resolved_limits import ResolvedLimits
from nvoken_generated.models.resume_invocation_request import ResumeInvocationRequest
from nvoken_generated.models.retention_policy import RetentionPolicy
from nvoken_generated.models.rotate_credential_request import RotateCredentialRequest
from nvoken_generated.models.rotate_provider_key_request import RotateProviderKeyRequest
from nvoken_generated.models.sampling import Sampling
from nvoken_generated.models.seed_message import SeedMessage
from nvoken_generated.models.seed_message_content import SeedMessageContent
from nvoken_generated.models.server_tool_use_block import ServerToolUseBlock
from nvoken_generated.models.session import Session
from nvoken_generated.models.session_compaction import SessionCompaction
from nvoken_generated.models.session_compaction_list import SessionCompactionList
from nvoken_generated.models.session_compaction_status import SessionCompactionStatus
from nvoken_generated.models.session_content_block import SessionContentBlock
from nvoken_generated.models.session_context import SessionContext
from nvoken_generated.models.session_fork_lineage import SessionForkLineage
from nvoken_generated.models.session_list import SessionList
from nvoken_generated.models.session_message import SessionMessage
from nvoken_generated.models.session_message_list import SessionMessageList
from nvoken_generated.models.session_message_role import SessionMessageRole
from nvoken_generated.models.session_options import SessionOptions
from nvoken_generated.models.stream_end_event import StreamEndEvent
from nvoken_generated.models.stream_end_reason import StreamEndReason
from nvoken_generated.models.stream_resync_event import StreamResyncEvent
from nvoken_generated.models.stream_resync_reason import StreamResyncReason
from nvoken_generated.models.structured_output_provenance import StructuredOutputProvenance
from nvoken_generated.models.submit_host_tool_results_request import SubmitHostToolResultsRequest
from nvoken_generated.models.submit_host_tool_results_request_results_inner import SubmitHostToolResultsRequestResultsInner
from nvoken_generated.models.submit_host_tool_results_response import SubmitHostToolResultsResponse
from nvoken_generated.models.tenant import Tenant
from nvoken_generated.models.tenant_credits import TenantCredits
from nvoken_generated.models.tenant_list import TenantList
from nvoken_generated.models.text_block import TextBlock
from nvoken_generated.models.text_input_block import TextInputBlock
from nvoken_generated.models.thinking_delta_event import ThinkingDeltaEvent
from nvoken_generated.models.tool_call import ToolCall
from nvoken_generated.models.tool_call_delivery import ToolCallDelivery
from nvoken_generated.models.tool_call_list import ToolCallList
from nvoken_generated.models.tool_call_mode import ToolCallMode
from nvoken_generated.models.tool_call_result_origin import ToolCallResultOrigin
from nvoken_generated.models.tool_call_status import ToolCallStatus
from nvoken_generated.models.tool_call_summary import ToolCallSummary
from nvoken_generated.models.tool_callback_context import ToolCallbackContext
from nvoken_generated.models.tool_callback_request import ToolCallbackRequest
from nvoken_generated.models.tool_callback_response import ToolCallbackResponse
from nvoken_generated.models.tool_choice import ToolChoice
from nvoken_generated.models.tool_declaration import ToolDeclaration
from nvoken_generated.models.tool_metrics import ToolMetrics
from nvoken_generated.models.tool_result_block import ToolResultBlock
from nvoken_generated.models.tool_use_block import ToolUseBlock
from nvoken_generated.models.trace import Trace
from nvoken_generated.models.trace_list import TraceList
from nvoken_generated.models.trace_span import TraceSpan
from nvoken_generated.models.trace_summary import TraceSummary
from nvoken_generated.models.transcript_snapshot import TranscriptSnapshot
from nvoken_generated.models.transcript_stream_event import TranscriptStreamEvent
from nvoken_generated.models.transcript_update_event import TranscriptUpdateEvent
from nvoken_generated.models.url_citation import URLCitation
from nvoken_generated.models.update_app_request import UpdateAppRequest
from nvoken_generated.models.update_org_request import UpdateOrgRequest
from nvoken_generated.models.update_session_request import UpdateSessionRequest
from nvoken_generated.models.update_session_request_metadata_value import UpdateSessionRequestMetadataValue
from nvoken_generated.models.usage_breakdown import UsageBreakdown
from nvoken_generated.models.usage_breakdown_item import UsageBreakdownItem
from nvoken_generated.models.usage_interval import UsageInterval
from nvoken_generated.models.usage_metrics import UsageMetrics
from nvoken_generated.models.usage_records import UsageRecords
from nvoken_generated.models.usage_timeseries import UsageTimeseries
from nvoken_generated.models.usage_timeseries_bucket import UsageTimeseriesBucket
from nvoken_generated.models.web_search_location import WebSearchLocation
from nvoken_generated.models.web_search_result_location_citation import WebSearchResultLocationCitation
from nvoken_generated.models.web_search_tool import WebSearchTool
from nvoken_generated.models.webhook_event import WebhookEvent
from nvoken_generated.models.webhook_target import WebhookTarget
