# coding: utf-8

"""
    nvoken Runtime API

    This focused contract defines nvoken's implemented background Runtime surface: durable Invocation admission, authoritative Invocation and Session reads, cursor-based transcript recovery, and resumable Session output streaming.  The Runtime API has no deletion, compaction, or retention-control operation. Authoritative records exposed by this contract are retained by default; the complete inventory and any future ordered-deletion contract are governed by the design packet's Data and retention section.  Inline and callback client tools, structured output, and reusable model provider credential lifecycle are included. Spec references and general administrative APIs remain outside this version.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from nvoken_generated.models.invocation_failure import InvocationFailure
from nvoken_generated.models.invocation_status import InvocationStatus
from nvoken_generated.models.model_provenance import ModelProvenance
from nvoken_generated.models.model_usage import ModelUsage
from nvoken_generated.models.structured_output_provenance import StructuredOutputProvenance
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvocationChange(BaseModel):
    """
    InvocationChange
    """ # noqa: E501
    invocation_id: Annotated[str, Field(strict=True)] = Field(description="UUIDv7 with the public `invk_` prefix.")
    revision: Annotated[int, Field(strict=True, ge=1)]
    status: InvocationStatus
    through_message_sequence: Optional[Annotated[int, Field(strict=True, ge=1)]]
    error: Optional[InvocationFailure]
    usage: Optional[ModelUsage]
    provenance: Optional[ModelProvenance]
    output: Optional[Dict[str, Any]]
    output_provenance: Optional[StructuredOutputProvenance]
    occurred_at: datetime
    __properties: ClassVar[List[str]] = ["invocation_id", "revision", "status", "through_message_sequence", "error", "usage", "provenance", "output", "output_provenance", "occurred_at"]

    @field_validator('invocation_id')
    def invocation_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^invk_[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$", value):
            raise ValueError(r"must validate the regular expression /^invk_[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvocationChange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of provenance
        if self.provenance:
            _dict['provenance'] = self.provenance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output_provenance
        if self.output_provenance:
            _dict['output_provenance'] = self.output_provenance.to_dict()
        # set to None if through_message_sequence (nullable) is None
        # and model_fields_set contains the field
        if self.through_message_sequence is None and "through_message_sequence" in self.model_fields_set:
            _dict['through_message_sequence'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if provenance (nullable) is None
        # and model_fields_set contains the field
        if self.provenance is None and "provenance" in self.model_fields_set:
            _dict['provenance'] = None

        # set to None if output (nullable) is None
        # and model_fields_set contains the field
        if self.output is None and "output" in self.model_fields_set:
            _dict['output'] = None

        # set to None if output_provenance (nullable) is None
        # and model_fields_set contains the field
        if self.output_provenance is None and "output_provenance" in self.model_fields_set:
            _dict['output_provenance'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvocationChange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invocation_id": obj.get("invocation_id"),
            "revision": obj.get("revision"),
            "status": obj.get("status"),
            "through_message_sequence": obj.get("through_message_sequence"),
            "error": InvocationFailure.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "usage": ModelUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "provenance": ModelProvenance.from_dict(obj["provenance"]) if obj.get("provenance") is not None else None,
            "output": obj.get("output"),
            "output_provenance": StructuredOutputProvenance.from_dict(obj["output_provenance"]) if obj.get("output_provenance") is not None else None,
            "occurred_at": obj.get("occurred_at")
        })
        return _obj
